id: PB6D7DB90
initial_creation_type: input
source_metadata:
  Title: Jñānālokālaṃkāra
  Editor: Study Group on Buddhist Sanskrit Literature
  Publisher: Taisho University
  Place of Publication: Tokyo
  Year: '2004'
  Āryasarvabuddhaviṣayāvatārajñānālokālaṃkāranāma mahāyānasūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2015'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T15:59:37.610492'
last_modified_at: '2022-03-08T15:59:37.610504'
